version: '3'
services:
  backend:
    image: builderboard-server-img
    ports:
      - "9000:8080"
    container_name: backend
  frontend:
    image: builderboard-web-img
    ports:
      - "4200:80"
    container_name: webapp
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: builderBoard
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    container_name: database
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9090:9000
      - 8080:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    container_name: portainer
volumes:
  portainer_data: