version: '3'
services:
  # proxy:
  #  image: traefik
  #  ports:
  #    - "80:80"
  #    - "8080:8080"
  #  command: --api.insecure=true --providers.docker --entrypoints.web.address=:80
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  container_name: traefik
  backend:
    image: builderboard-server-img
    # labels:
    #  - # "traefik.http.routers.backend.rule=Path(`/bbb/`)"
    #  - "traefik.enable=true"
    #  - "traefik.port=9000"
    ports:
      - "9000:8080"
    container_name: backend
  frontend:
    image: builderboard-web-img
    # labels:
    #  - # "traefik.http.routers.frontend.rule=Path(`/builderboard/`)"
    #  - "traefik.http.routers.frontend.entrypoints=web"
    #  - "traefik.enable=true"
    #  - "traefik.port=4200"
    ports:
      - "4200:80"
    container_name: webapp
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: builderBoard
      MYSQL_ROOT_PASSWORD: root
    # labels:
    #  - "traefik.enable=true"
    #  - "traefik.port=3306"
    ports:
      - "3306:3306"
    container_name: database
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9090:9000
      - 8080:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    container_name: portainer
volumes:
  portainer_data: